# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: DuckDB
email: quack@duckdb.org
description: >- # this means to ignore newlines until "baseurl:"
  DuckDB is an in-process SQL database management system focused on analytical query processing. It is designed to be easy to install and easy to use. DuckDB has no external dependencies. DuckDB has bindings for C/C++, Python, R, Java, Node.js, Go and other languages.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://duckdb.org" # the base hostname & protocol for your site, e.g. http://example.com
# Set current codename of DuckDB and version numbers of DuckDB clients
current_duckdb_codename: "Andium"
current_short_duckdb_version: "1.5"
current_short_duckdb_lts_version: "1.4"
preview_short_duckdb_version: 1.5-dev"
current_duckdb_version: "1.5.0"
current_duckdb_hash: "TODO"
current_duckdb_odbc_version: "1.4.4.0"
current_duckdb_odbc_short_version: "1.4.4"
current_duckdb_go_version: "1.4.4"
current_duckdb_node_neo_version: "1.4.4"
current_duckdb_r_version: "1.4.4"
current_duckdb_rust_version: "1.4.4"
current_duckdb_wasm_version: "1.4.4"
current_duckdb_csharp_version: "1.4.4"
current_duckdb_dart_version: "1.4.4"
current_duckdb_java_version: "1.4.4.0"
current_duckdb_java_short_version: "1.4.4"
livereload: true
highlighter: rouge
incremental: false
# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  smart_quotes: ["apos", "apos", "quot", "quot"]
theme: minima
plugins:
  - jekyll-regex-replace
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-git-hash
  - jekyll-toc

collections:
  events:
    output: true
    permalink: /events/:year/:month/:day/:title/
  library:
    output: true
    permalink: /library/:title/
  everywhere:
    output: true
    permalink: /everywhere/:title/

excerpt_separator: <!--more-->
future: true

last-modified-at:
  date-format: '%Y-%m-%d'

twitter:
  username: DuckDB
  card: summary

github:
  source:
    branch: main
  repository_url: "https://github.com/duckdb/duckdb-web"

defaults:
  - scope:
      path: ""
    values:
      image: /images/sharingduckdb.jpg
      toc: true

repository: "duckdb/duckdb-web"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

star_count: '36.0k'

toc:
  min_level: 1
  max_level: 3
  ordered_list: false

exclude: ['Gemfile', 'Gemfile.lock', 'node_modules', 'vendor/bundle', 'vendor/cache', 'vendor/gems', 'vendor/ruby', 'bundle']

include:
  - docs/stable/clients/python/reference/objects.inv
  - docs/preview/clients/python/reference/objects.inv
