data-dir: .
input-file: duckdb-docs.md
output-file: duckdb-docs.pdf
from: markdown_github+header_attributes+tex_math_dollars-smart
to: pdf
metadata-file: metadata.yaml
template: eisvogel2.tex
pdf-engine: xelatex
syntax-definition: sql-duckdb.xml
table-of-contents: true
toc-depth: 3
top-level-division: part
variables:
  book: true
  numbersections: false
  titlepage: true
  titlepage-color: F5F5F5
  titlepage-logo: ../images/duckdb-logo.pdf
  titlepage-rule-color: FFF100
  titlepage-rule-height: 20
  urlcolor: blue
