name: Link Checker

on:
  schedule:
    - cron: "0 4 * * *"  # run every day at 4AM

jobs:
  LinkChecker:
    name: Link Checker
    runs-on: ubuntu-24.04
    if: github.ref == 'refs/heads/main' && github.repository == 'duckdb/duckdb-web'
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Set up Python 3.9
        uses: actions/setup-python@v6
        with:
          python-version: '3.9'

      - run: pip install linkchecker --user

      - name: Link Checker ignoring the old documentation pages (and keeping the stable and preview pages)
        run: |
          linkchecker https://duckdb.org/ --ignore-url 'https?://duckdb\.org/docs/[0-9]*.[0-9]*/.*' --config .github/linkchecker/linkchecker.conf --file-output html/utf-8/report.html
          echo $?

      - run: cat report.html >> ${GITHUB_STEP_SUMMARY}
        if: success() || failure()
