name: Discord stackoverflow bot 

on:
  workflow_dispatch:
  schedule:
    - cron: "0 11 * * *"

jobs:
  build:
    name: Discord Stack Overflow bot 
    runs-on: ubuntu-22.04
    if: github.repository == 'duckdb/duckdb-web'

    steps:
      - uses: actions/checkout@v5

      - name: Setting up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.8"
          architecture: "x64"
          cache: 'pip'
          
      - run: pip install duckdb requests pytz

      - name: Trigger StackOverflow Bot
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          python3 ./scripts/stackoverflow_bot.py
